"""Generate the LaTeX tables of the revision from the result CSVs.

Every number that goes into the response letter or the revised manuscript is
produced here, never copied by hand.  Rerun after any new experiment lands in
``result/``; the letter and the manuscript pick the fragments up via ``\\input``.

Usage (from the repository root)::

    python -m paper_assets.make_tables            # -> paper_assets/tables/*.tex

Each fragment is a bare ``tabular`` plus a comment header naming its source
files, so the surrounding ``table`` environment (caption, label, colour) stays
under the author's control in the document that includes it.
"""
from __future__ import annotations

import glob
import os
import sys

import pandas as pd

try:
    from scipy import stats as scipy_stats
except ImportError:  # pragma: no cover
    scipy_stats = None

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tables")
RULES = ["MQ-ND", "MQ-MinRQ", "MQ-MI", "MI-MinRQ", "MI-MI"]


def load(pattern: str) -> pd.DataFrame:
    paths = sorted(glob.glob(f"result/{pattern}/eval_results.csv"))
    if not paths:
        return pd.DataFrame()
    frames = []
    for path in paths:
        frame = pd.read_csv(path)
        frame["src"] = path.split(os.sep)[1]
        frames.append(frame)
    return pd.concat(frames, ignore_index=True)


def fmt(value, digits=1) -> str:
    return "--" if pd.isna(value) else f"{value:.{digits}f}"


def mean_std(series: pd.Series, digits=1) -> str:
    if len(series) == 0:
        return "--"
    if len(series) == 1 or series.std(ddof=1) < 1e-9:
        return fmt(series.mean(), digits)
    return f"{series.mean():.{digits}f} $\\pm$ {series.std(ddof=1):.{digits}f}"


def write(name: str, sources: list, lines: list) -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, name)
    header = ["% Generated by paper_assets/make_tables.py -- do not edit by hand.",
              "% Sources: " + ", ".join(sources)]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(header + lines) + "\n")
    print(f"  -> {path}")


# --------------------------------------------------------------------------- #
def table_ratio() -> None:
    """Picker:robot ratio scenarios -- E0 + E1 + E2 on the lam40 stream."""
    df = load("e[012]_*")
    if df.empty:
        return
    df = df[df["instance_id"] == "lam40"]
    rows = []
    order = []
    for src, group in df.groupby("src"):
        k = int(group["n_pickers"].iloc[0])
        r = int(group["n_robots"].iloc[0])
        order.append((k + r, k, r, src))
    seen = set()
    configs = []
    for total, k, r, src in sorted(order):
        if (k, r) in seen:
            continue
        seen.add((k, r))
        configs.append((k, r))

    for k, r in configs:
        group = df[(df["n_pickers"] == k) & (df["n_robots"] == r)]
        sappo = group[group["method"] == "SAPPO"]["mean_flow_time"]
        rules = group[group["method"] != "SAPPO"].groupby("method")["mean_flow_time"].mean()
        best_rule = rules.idxmin() if len(rules) else "--"
        best_val = rules.min() if len(rules) else float("nan")
        gap = ((best_val - sappo.mean()) / best_val * 100) if len(sappo) and len(rules) else float("nan")
        rows.append(f"{k}:{r} & {k} & {r} & {mean_std(sappo)} & "
                    f"{best_rule} & {fmt(best_val)} & {fmt(gap)}\\% \\\\")

    write("tab_ratio.tex",
          sorted(df["src"].unique()),
          ["\\begin{tabular}{lcccccc}", "\\toprule",
           "Ratio $K{:}R$ & $K$ & $R$ & SAPPO $\\bar{F}$ & Best rule & Rule $\\bar{F}$ & Gap \\\\",
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def table_capacity() -> None:
    """Carrying-capacity sensitivity -- E0 (C=1), E7, E9 and the rule sweep."""
    df = pd.concat([load("e0_*"), load("e7_*"), load("e9_*"), load("rules_capacity_*")],
                   ignore_index=True) if not load("e0_*").empty else pd.DataFrame()
    if df.empty:
        return
    df = df[df["instance_id"] == "lam40"]

    capacities = sorted(df["robot_capacity"].unique())
    methods = ["SAPPO"] + [m for m in RULES if m in set(df["method"])]
    has_plus = not df[(df["method"] == "SAPPO") & (df["state_channels"] != "base")].empty

    header = "Method & " + " & ".join(f"$C={int(c)}$" for c in capacities) + " \\\\"
    rows = []
    for method in methods:
        cells = []
        for capacity in capacities:
            sel = df[(df["method"] == method) & (df["robot_capacity"] == capacity)]
            if method == "SAPPO":
                sel = sel[sel["state_channels"] == "base"]
            cells.append(mean_std(sel["mean_flow_time"]))
        rows.append(f"{method} & " + " & ".join(cells) + " \\\\")
    if has_plus:
        cells = []
        for capacity in capacities:
            sel = df[(df["method"] == "SAPPO") & (df["robot_capacity"] == capacity)
                     & (df["state_channels"] != "base")]
            cells.append(mean_std(sel["mean_flow_time"]))
        rows.append("SAPPO (+agent channels) & " + " & ".join(cells) + " \\\\")

    write("tab_capacity.tex",
          sorted(df["src"].unique()),
          [f"\\begin{{tabular}}{{l{'c' * len(capacities)}}}", "\\toprule", header,
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def table_gamma() -> None:
    """Discount-factor ablation -- E4, three streams, mean +/- std over runs."""
    df = load("e4_*")
    if df.empty:
        return
    df = df[df["method"] == "SAPPO"]
    streams = sorted(df["instance_id"].unique())
    rows = []
    for gamma, group in sorted(df.groupby("gamma")):
        cells = [mean_std(group[group["instance_id"] == s]["mean_flow_time"]) for s in streams]
        overall = group.groupby(["instance_id", "run_id"])["mean_flow_time"].mean()
        rows.append(f"{gamma:.2f} & " + " & ".join(cells)
                    + f" & {group['mean_flow_time'].mean():.1f} \\\\")
    header = ("$\\gamma$ & " + " & ".join(
        f"$1/\\lambda={s.replace('lam', '')}$" for s in streams) + " & Overall \\\\")
    write("tab_gamma.tex", sorted(df["src"].unique()),
          [f"\\begin{{tabular}}{{l{'c' * len(streams)}c}}", "\\toprule", header,
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def table_state() -> None:
    """State-channel ablation -- E0 (base) vs E5 (plus_agent), with a paired test."""
    base = load("e0_*")
    plus = load("e5_*")
    if base.empty or plus.empty:
        return
    base = base[base["method"] == "SAPPO"].assign(group="Base (4 channels)")
    plus = plus[plus["method"] == "SAPPO"].assign(group="+ agent channels (6)")
    df = pd.concat([base, plus], ignore_index=True)
    streams = sorted(df["instance_id"].unique())

    rows = []
    for group_name in ["Base (4 channels)", "+ agent channels (6)"]:
        group = df[df["group"] == group_name]
        cells = [mean_std(group[group["instance_id"] == s]["mean_flow_time"]) for s in streams]
        rows.append(f"{group_name} & " + " & ".join(cells)
                    + f" & {group['mean_flow_time'].mean():.1f} \\\\")

    note = ""
    if scipy_stats is not None:
        b = base.groupby(["instance_id", "run_id"])["mean_flow_time"].mean()
        p = plus.groupby(["instance_id", "run_id"])["mean_flow_time"].mean()
        common = b.index.intersection(p.index)
        if len(common) >= 2:
            t_stat, p_val = scipy_stats.ttest_rel(b[common], p[common])
            note = (f"% paired t-test over {len(common)} (stream, run) pairs: "
                    f"t = {t_stat:.3f}, p = {p_val:.4f}")

    header = ("State & " + " & ".join(
        f"$1/\\lambda={s.replace('lam', '')}$" for s in streams) + " & Overall \\\\")
    write("tab_state.tex", sorted(df["src"].unique()),
          ([note] if note else []) +
          [f"\\begin{{tabular}}{{l{'c' * len(streams)}c}}", "\\toprule", header,
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def table_picktime() -> None:
    """Picking-time sensitivity -- E0 (tau=10) + E6, SAPPO vs the five rules."""
    df = pd.concat([load("e0_*"), load("e6_*")], ignore_index=True)
    if df.empty:
        return
    df = df[df["instance_id"] == "lam40"]
    taus = sorted(df["pick_time"].unique())
    rows = []
    for method in ["SAPPO"] + RULES:
        cells = []
        for tau in taus:
            sel = df[(df["method"] == method) & (df["pick_time"] == tau)]
            cells.append(mean_std(sel["mean_flow_time"]))
        rows.append(f"{method} & " + " & ".join(cells) + " \\\\")
    header = ("Method & " + " & ".join(
        f"$\\tau_{{\\mathrm{{pick}}}}={tau:g}$\\,s" for tau in taus) + " \\\\")
    write("tab_picktime.tex", sorted(df["src"].unique()),
          [f"\\begin{{tabular}}{{l{'c' * len(taus)}}}", "\\toprule", header,
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def table_layout() -> None:
    """Layout variant -- E0 (two cross-aisles) vs E8 (middle cross-aisle added)."""
    df = pd.concat([load("e0_*"), load("e8_*")], ignore_index=True)
    if df.empty:
        return
    df = df[df["instance_id"] == "lam40"]
    layouts = [("two_cross_aisles", "Bottom + top cross-aisles (Eq. 2)"),
               ("three_cross_aisles", "+ middle cross-aisle")]
    rows = []
    for key, label in layouts:
        group = df[df["layout"] == key]
        if group.empty:
            continue
        sappo = group[group["method"] == "SAPPO"]["mean_flow_time"]
        rules = group[group["method"] != "SAPPO"].groupby("method")["mean_flow_time"].mean()
        rows.append(f"{label} & {mean_std(sappo)} & {rules.idxmin()} & {fmt(rules.min())} \\\\")
    write("tab_layout.tex", sorted(df["src"].unique()),
          ["\\begin{tabular}{lccc}", "\\toprule",
           "Layout & SAPPO $\\bar{F}$ & Best rule & Rule $\\bar{F}$ \\\\",
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def table_training_cost() -> None:
    """Training cost vs problem size -- the E3 summary."""
    path = "result/training_cost_summary.csv"
    if not os.path.exists(path):
        return
    df = pd.read_csv(path)
    grouped = (df.groupby(["n_pickers", "n_robots", "n_actions", "n_parameters",
                           "n_episodes"], as_index=False)
                 .agg(runs=("run_name", "count"),
                      wall_clock_s=("wall_clock_s", "mean"),
                      decisions_per_second=("decisions_per_second", "mean"))
                 .sort_values("n_actions"))
    rows = []
    for _, row in grouped.iterrows():
        rows.append(f"{int(row['n_pickers'])} & {int(row['n_robots'])} & "
                    f"{int(row['n_actions'])} & {row['n_parameters'] / 1e6:.1f} & "
                    f"{int(row['n_episodes'])} & {int(row['runs'])} & "
                    f"{row['wall_clock_s'] / 3600:.1f} & "
                    f"{row['decisions_per_second']:.0f} \\\\")
    write("tab_training_cost.tex", [path],
          ["\\begin{tabular}{cccccccc}", "\\toprule",
           "$K$ & $R$ & $|\\mathcal{A}|$ & Params ($\\times 10^6$) & Episodes & Runs & "
           "Wall clock (h) & Decisions/s \\\\",
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def main() -> None:
    if not os.path.isdir("result"):
        sys.exit("run from the repository root (result/ not found)")
    print("generating LaTeX fragments:")
    table_ratio()
    table_capacity()
    table_gamma()
    table_state()
    table_picktime()
    table_layout()
    table_training_cost()
    print("done")


if __name__ == "__main__":
    main()
