"""Generate every LaTeX table of the revision from the result CSVs.

No number that appears in the manuscript or the response letter is ever copied
by hand: rerun this after any experiment and ``\\input`` the fragments.

    python -m paper_assets.make_tables        # -> paper_assets/tables/*.tex

Expected result layout (produced by the experiments/ scripts):

    result/main/eval_results.csv              main comparison (Tables 5, 7, 8, 9)
    result/scale/K<k>_R<r>/eval_results.csv   resource scale (Table 10)
    result/capacity/c<C>/...                  carrying capacity (R1.5)
    result/picktime/tau<t>/...                picking time (R1.4)
    result/layout/three/...                   middle cross-aisle (R1.3)
    result/gamma/g<g>/...                     discount ablation (R2.3)
    result/state_plus/...                     state ablation (R2.4)
    result/grid/<AxB>/...                     warehouse grids (Tables 11, 12)
    result/train_*/training_cost.csv          training cost (R2.1)

Cell conventions: RL methods show "mean +/- std" over the 3 stochastic
evaluation samples; the deterministic rules show their single value.  D-bar is
the true wall-clock decision time in milliseconds.
"""
from __future__ import annotations

import glob
import os
from typing import List, Optional, Sequence

import pandas as pd

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tables")
RL_METHODS = ["SAPPO", "AG-DQN", "HSDDQN", "SOA+A2C", "DRLG"]
RULES = ["MQ-ND", "MQ-MinRQ", "MQ-MI", "MI-MinRQ", "MI-MI"]


def load(path_glob: str) -> pd.DataFrame:
    paths = sorted(glob.glob(path_glob, recursive=True))
    if not paths:
        return pd.DataFrame()
    frames = [pd.read_csv(p).assign(source=p) for p in paths]
    return pd.concat(frames, ignore_index=True)


def cell(group: pd.DataFrame, digits: int = 1) -> str:
    values = group["mean_flow_time"]
    if len(values) == 0:
        return "--"
    if len(values) == 1 or values.std(ddof=1) < 1e-9:
        return f"{values.mean():.{digits}f}"
    return f"{values.mean():.{digits}f} $\\pm$ {values.std(ddof=1):.{digits}f}"


def dbar(group: pd.DataFrame) -> str:
    return "--" if group.empty else f"{group['decision_time_ms'].mean():.2f}"


def write(name: str, sources: Sequence[str], lines: List[str]) -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(
            ["% Generated by paper_assets/make_tables.py -- do not edit by hand.",
             "% Sources: " + ", ".join(sorted(set(sources)))] + lines) + "\n")
    print(f"  -> {path}")


def _method_table(df: pd.DataFrame, methods: List[str], name: str) -> None:
    """27-row case table: F-bar and D-bar per method (Tables 5 and 7)."""
    methods = [m for m in methods if m in set(df["method"])]
    if not methods or df.empty:
        return
    header = ("Case & " + " & ".join(
        f"\\multicolumn{{2}}{{c}}{{{m}}}" for m in methods) + " \\\\")
    sub = " & " + " & ".join("$\\bar{F}$ & $\\bar{D}$ (ms)" for _ in methods) + " \\\\"
    rows = []
    for case in sorted(df["case"].unique()):
        cells = []
        for method in methods:
            group = df[(df["case"] == case) & (df["method"] == method)]
            cells.append(f"{cell(group)} & {dbar(group)}")
        rows.append(f"{case} & " + " & ".join(cells) + " \\\\")
    avg = []
    for method in methods:
        group = df[df["method"] == method]
        per_case = group.groupby("case")["mean_flow_time"].mean()
        avg.append(f"{per_case.mean():.1f} & {group['decision_time_ms'].mean():.2f}")
    rows += ["\\midrule", "\\textbf{AVG} & " + " & ".join(avg) + " \\\\"]
    write(name, list(df["source"].unique()),
          [f"\\begin{{tabular}}{{l{'cc' * len(methods)}}}", "\\toprule", header, sub,
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def tables_main() -> None:
    df = load("result/main/eval_results.csv")
    if df.empty:
        return
    _method_table(df, ["SAPPO"] + RULES, "tab_main_rules.tex")      # Table 5
    _method_table(df, RL_METHODS, "tab_main_rl.tex")                # Table 7


def table_stats() -> None:
    """Tables 8-9: paired significance tests against SAPPO over the 27 cases."""
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from result.stats import paired_tests

    df = load("result/main/eval_results.csv")
    if df.empty:
        return
    tests = paired_tests(df)
    if tests.empty:
        return
    rows = []
    for _, r in tests.iterrows():
        rows.append(f"{r['comparison'].replace('SAPPO vs ', '')} & "
                    f"{r['avg_gap'] * 100:.1f}\\% & "
                    f"{r.get('t_statistic', float('nan')):.2f} & "
                    f"{r.get('p_value_t', float('nan')):.4f} & "
                    f"{r.get('w_statistic', float('nan')):.1f} & "
                    f"{r.get('p_value_wilcoxon', float('nan')):.4f} & "
                    f"{r['cohens_d']:.2f} \\\\")
    write("tab_stats.tex", list(df["source"].unique()),
          ["\\begin{tabular}{lcccccc}", "\\toprule",
           "Comparison & Avg. gap & $t$ & $p$ ($t$) & $W$ & $p$ ($W$) & Cohen's $d$ \\\\",
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def table_scale() -> None:
    """Table 10: one global policy evaluated zero-shot across fleets."""
    frames = [load("result/main/eval_results.csv"), load("result/scale/**/eval_results.csv")]
    df = pd.concat([f for f in frames if not f.empty], ignore_index=True) \
        if any(not f.empty for f in frames) else pd.DataFrame()
    if df.empty:
        return
    df = df[df["mean_interarrival"] == 40.0]
    fleets = sorted({(int(k), int(r)) for k, r in zip(df["n_pickers"], df["n_robots"])})
    methods = [m for m in RL_METHODS if m in set(df["method"])]
    rows = []
    for k, r in fleets:
        sub = df[(df["n_pickers"] == k) & (df["n_robots"] == r)]
        cells = [cell(sub[sub["method"] == m]) for m in methods]
        rows.append(f"{k} & {r} & " + " & ".join(cells) + " \\\\")
    write("tab_scale.tex", list(df["source"].unique()),
          [f"\\begin{{tabular}}{{cc{'c' * len(methods)}}}", "\\toprule",
           "$K$ & $R$ & " + " & ".join(methods) + " \\\\", "\\midrule"]
          + rows + ["\\bottomrule", "\\end{tabular}"])


def _sensitivity_table(base_glob: str, axis_column: str, axis_fmt, name: str,
                       baseline_glob: str = "result/main/eval_results.csv",
                       baseline_filter: Optional[dict] = None) -> None:
    frames = [load(baseline_glob), load(base_glob)]
    df = pd.concat([f for f in frames if not f.empty], ignore_index=True) \
        if any(not f.empty for f in frames) else pd.DataFrame()
    if df.empty:
        return
    for key, value in (baseline_filter or {}).items():
        df = df[df[key] == value]
    axis_values = sorted(df[axis_column].unique())
    methods = [m for m in RL_METHODS + RULES if m in set(df["method"])]
    rows = []
    for method in methods:
        cells = [cell(df[(df["method"] == method) & (df[axis_column] == v)])
                 for v in axis_values]
        rows.append(f"{method} & " + " & ".join(cells) + " \\\\")
    header = "Method & " + " & ".join(axis_fmt(v) for v in axis_values) + " \\\\"
    write(name, list(df["source"].unique()),
          [f"\\begin{{tabular}}{{l{'c' * len(axis_values)}}}", "\\toprule", header,
           "\\midrule"] + rows + ["\\bottomrule", "\\end{tabular}"])


def table_capacity() -> None:
    _sensitivity_table("result/capacity/**/eval_results.csv", "robot_capacity",
                       lambda v: f"$C={int(v)}$", "tab_capacity.tex",
                       baseline_filter={"mean_interarrival": 40.0})


def table_picktime() -> None:
    _sensitivity_table("result/picktime/**/eval_results.csv", "pick_time",
                       lambda v: f"$\\tau_{{\\mathrm{{pick}}}}={v:g}$\\,s",
                       "tab_picktime.tex",
                       baseline_filter={"mean_interarrival": 40.0})


def table_layout() -> None:
    _sensitivity_table("result/layout/**/eval_results.csv", "layout",
                       lambda v: ("Two cross-aisles" if v == "two_cross_aisles"
                                  else "+ middle cross-aisle"),
                       "tab_layout.tex",
                       baseline_filter={"mean_interarrival": 40.0})


def table_gamma() -> None:
    """R2.3: discount ablation.  gamma=0.99 rows come from the main run."""
    frames = [load("result/main/eval_results.csv"), load("result/gamma/**/eval_results.csv")]
    df = pd.concat([f for f in frames if not f.empty], ignore_index=True) \
        if any(not f.empty for f in frames) else pd.DataFrame()
    if df.empty:
        return
    df = df[df["method"] == "SAPPO"]
    lams = sorted(df["mean_interarrival"].unique())
    rows = []
    for gamma in sorted(df["gamma"].unique()):
        sub = df[df["gamma"] == gamma]
        cells = [cell(sub[sub["mean_interarrival"] == lam]) for lam in lams]
        rows.append(f"{gamma:.2f} & " + " & ".join(cells)
                    + f" & {sub['mean_flow_time'].mean():.1f} \\\\")
    write("tab_gamma.tex", list(df["source"].unique()),
          [f"\\begin{{tabular}}{{l{'c' * len(lams)}c}}", "\\toprule",
           "$\\gamma$ & " + " & ".join(f"$1/\\lambda={lam:g}$" for lam in lams)
           + " & Overall \\\\", "\\midrule"] + rows
          + ["\\bottomrule", "\\end{tabular}"])


def table_state() -> None:
    """R2.4: base observation vs + per-robot channels."""
    base = load("result/main/eval_results.csv")
    plus = load("result/state_plus/**/eval_results.csv")
    if base.empty or plus.empty:
        return
    base = base[base["method"] == "SAPPO"].assign(group="Base observation")
    plus = plus[plus["method"] == "SAPPO"].assign(group="+ per-robot channels")
    df = pd.concat([base, plus], ignore_index=True)
    lams = sorted(df["mean_interarrival"].unique())
    rows = []
    for group_name in ["Base observation", "+ per-robot channels"]:
        sub = df[df["group"] == group_name]
        cells = [cell(sub[sub["mean_interarrival"] == lam]) for lam in lams]
        rows.append(f"{group_name} & " + " & ".join(cells)
                    + f" & {sub['mean_flow_time'].mean():.1f} \\\\")
    write("tab_state.tex", list(df["source"].unique()),
          [f"\\begin{{tabular}}{{l{'c' * len(lams)}c}}", "\\toprule",
           "Observation & " + " & ".join(f"$1/\\lambda={lam:g}$" for lam in lams)
           + " & Overall \\\\", "\\midrule"] + rows
          + ["\\bottomrule", "\\end{tabular}"])


def table_grid() -> None:
    """Tables 11-12: warehouse-grid sensitivity (per-grid training)."""
    frames = [load("result/main/eval_results.csv").assign(grid="9x20"),
              load("result/grid/**/eval_results.csv")]
    df = pd.concat([f for f in frames if not f.empty], ignore_index=True) \
        if any(not f.empty for f in frames) else pd.DataFrame()
    if df.empty or "grid" not in df.columns:
        return
    if df["grid"].isna().any():
        df.loc[df["grid"].isna(), "grid"] = (
            df.loc[df["grid"].isna(), "n_aisles"].astype(int).astype(str) + "x"
            + df.loc[df["grid"].isna(), "n_positions"].astype(int).astype(str))
    df = df[(df["mean_interarrival"] == 40.0) & (df["n_pickers"] == 3)
            & (df["n_robots"] == 6)]
    methods = [m for m in RL_METHODS + RULES if m in set(df["method"])]
    rows = []
    for grid in sorted(df["grid"].unique()):
        sub = df[df["grid"] == grid]
        n_w, n_l = grid.split("x")
        cells = [cell(sub[sub["method"] == m]) for m in methods]
        rows.append(f"{n_w} & {n_l} & " + " & ".join(cells) + " \\\\")
    write("tab_grid.tex", list(df["source"].unique()),
          [f"\\begin{{tabular}}{{cc{'c' * len(methods)}}}", "\\toprule",
           "$N_w$ & $N_l$ & " + " & ".join(methods) + " \\\\", "\\midrule"]
          + rows + ["\\bottomrule", "\\end{tabular}"])


def table_ratio() -> None:
    """R1.2: cases and fleets reorganised by picker : robot ratio (lambda = 40)."""
    frames = [load("result/main/eval_results.csv"), load("result/scale/**/eval_results.csv")]
    df = pd.concat([f for f in frames if not f.empty], ignore_index=True) \
        if any(not f.empty for f in frames) else pd.DataFrame()
    if df.empty:
        return
    df = df[df["mean_interarrival"] == 40.0]
    rows = []
    for (k, r) in sorted({(int(a), int(b)) for a, b in zip(df["n_pickers"], df["n_robots"])},
                         key=lambda kr: (kr[0] + kr[1], kr)):
        sub = df[(df["n_pickers"] == k) & (df["n_robots"] == r)]
        sappo = sub[sub["method"] == "SAPPO"]
        rules = sub[sub["method"].isin(RULES)].groupby("method")["mean_flow_time"].mean()
        if sappo.empty or rules.empty:
            continue
        best_rule = rules.idxmin()
        gap = (rules.min() - sappo["mean_flow_time"].mean()) / rules.min() * 100
        rows.append(f"{k}:{r} & {k} & {r} & {cell(sappo)} & {best_rule} & "
                    f"{rules.min():.1f} & {gap:.1f}\\% \\\\")
    if rows:
        write("tab_ratio.tex", list(df["source"].unique()),
              ["\\begin{tabular}{lcccccc}", "\\toprule",
               "Ratio $K{:}R$ & $K$ & $R$ & SAPPO $\\bar{F}$ & Best rule & "
               "Rule $\\bar{F}$ & Gap \\\\", "\\midrule"] + rows
              + ["\\bottomrule", "\\end{tabular}"])


def table_training_cost() -> None:
    paths = sorted(glob.glob("result/*/training_cost.csv"))
    if not paths:
        return
    df = pd.concat([pd.read_csv(p) for p in paths], ignore_index=True)
    df = df.sort_values(["grid", "algorithm"])
    rows = []
    for _, r in df.iterrows():
        rows.append(f"{r['algorithm']} & {r['grid']} & {int(r['n_actions'])} & "
                    f"{r['n_parameters'] / 1e6:.1f} & {int(r['n_episodes'])} & "
                    f"{r['wall_clock_s'] / 3600:.1f} & "
                    f"{r['decisions_per_second']:.0f} \\\\")
    write("tab_training_cost.tex", paths,
          ["\\begin{tabular}{lcccccc}", "\\toprule",
           "Algorithm & Grid & $|\\mathcal{A}|$ & Params ($\\times 10^6$) & Episodes & "
           "Wall clock (h) & Decisions/s \\\\", "\\midrule"] + rows
          + ["\\bottomrule", "\\end{tabular}"])


def main() -> None:
    if not os.path.isdir("result"):
        raise SystemExit("run from the repository root (result/ not found)")
    print("generating LaTeX fragments:")
    tables_main()
    table_stats()
    table_scale()
    table_capacity()
    table_picktime()
    table_layout()
    table_gamma()
    table_state()
    table_grid()
    table_ratio()
    table_training_cost()
    print("done")


if __name__ == "__main__":
    main()
